// <auto-generated />
using AU.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AU.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220327133423_CreatedInitial")]
    partial class CreatedInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AU.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hoodies",
                            Url = "hoodie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beanie",
                            Url = "beanie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "T-Shirt",
                            Url = "tshirt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mugs",
                            Url = "mug"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chairs",
                            Url = "chair"
                        });
                });

            modelBuilder.Entity("AU.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Warm and cosey, available in mutliple colours and sizes.",
                            Image = "hoodie",
                            Name = "Hoodie",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Stylish headwear to keep warm as well as represent the team",
                            Image = "beanie",
                            Name = "Beanie",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Customised and ergonimically designed mug for the warmest brews",
                            Image = "",
                            Name = "Mug",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Stylish 2019 Edition Team T-Shirt",
                            Image = "tshirt",
                            Name = "T-Shirt",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Styilish 2020 Edition Team Hoodie",
                            Image = "hoodie2020",
                            Name = "Hoodie 2020E",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Secret Labs sponsor chair",
                            Image = "chair",
                            Name = "Secret Chair",
                            Price = 299.99m
                        });
                });

            modelBuilder.Entity("AU.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DarkTheme")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Notifications")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AU.Shared.Models.Product", b =>
                {
                    b.HasOne("AU.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
